{
 "title": "Scoring Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1s",
 "panels": [
  {
   "title": "Скорость записи скорингов в БД",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "rate(scorings_total[5s])", "legendFormat": "Записей в секунду" }
   ]
  },
  {
   "title": "Среднее время записи в БД",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(scoring_db_write_seconds_sum[5s]) / rate(scoring_db_write_seconds_count[5s])",
     "legendFormat": "Avg Write Time"
    }
   ]
  },
  {
   "title": "Всего выявлено мошеннических транзакций",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "fraud_detected_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Распределение записанных скоров во времени",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(increase(scoring_fraud_score_bucket[30s])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}